Numpy Assignment -Feb 02 19

In [94]:
# 1. Write a Python program to create a vector with values ranging from 10 to 49
import numpy as np
x=np.array((1,2,3))
y=np.array((10))
#?np.array()
#print(x+3)

a = [1,2,3,4,5]
b = [10,20,30,40]
c=[val +2 for val in a]
#?range
d=[val+1 for val in range(9,49,1)]
print(d)
e=np.array(np.arange(10,50,1))
print(e)
#f=np.array(np.linspace(10,51,40))
print(f)
#print('Sum is ' , np.sum(f))


[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10.         11.05128205 12.1025641  13.15384615 14.20512821 15.25641026
 16.30769231 17.35897436 18.41025641 19.46153846 20.51282051 21.56410256
 22.61538462 23.66666667 24.71794872 25.76923077 26.82051282 27.87179487
 28.92307692 29.97435897 31.02564103 32.07692308 33.12820513 34.17948718
 35.23076923 36.28205128 37.33333333 38.38461538 39.43589744 40.48717949
 41.53846154 42.58974359 43.64102564 44.69230769 45.74358974 46.79487179
 47.84615385 48.8974359  49.94871795 51.        ]


2. Write a Python program to reverse a vector (first element becomes last)

In [98]:

d = np.array(np.arange(10))
#Ans : 
x = np.flip(d,0)
#e=d.reshape(2,5)
print(x)

[9 8 7 6 5 4 3 2 1 0]


 3.Write a Python program to create a 3x3 matrix with values ranging from 0 to 8

In [101]:
#Ans : 
f=np.arange(0,9,1).reshape(3,3)
print(f)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Ques 4. Write a Python program to find indices of non-zero elements from [1,2,0,0,4,0]

In [105]:
#Ans:
x=np.array([1,2,0,0,4,0]).nonzero()
print(x)


(array([0, 1, 4]),)


Ques 5. Write a Python program to create a 3x3x3 array with random values

In [117]:
#Ans:
x=np.random.rand(3,3,3)
y=np.array([1,2,3,4,5,6,7,8,9])
#y.rand(3,3,3)
?xrand
print(x)
print(y)

Object `xrand` not found.
[[[0.5311178  0.92556929 0.29944998]
  [0.03636891 0.52088815 0.85644807]
  [0.0240163  0.55716387 0.54384881]]

 [[0.28570062 0.67496243 0.09018528]
  [0.98925378 0.33761643 0.29232066]
  [0.94110093 0.0537649  0.8978639 ]]

 [[0.33576545 0.70527242 0.12078616]
  [0.54853294 0.48390731 0.11164289]
  [0.55239231 0.008627   0.35952988]]]
[1 2 3 4 5 6 7 8 9]


Ques 6. Write a Python program to create a 10x10 array with random values and 
find the minimum and maximum values

In [133]:
xx=np.random.rand(10,10)
print(xx)
print('Min ',xx.min())
print('Max ' ,xx.max())

[[0.82860958 0.5818999  0.10704652 0.8489348  0.03300209 0.98156947
  0.52665097 0.09400356 0.41045695 0.09836525]
 [0.92559495 0.26888927 0.45712144 0.83081382 0.00715753 0.84617955
  0.90569139 0.62726997 0.43721655 0.15051303]
 [0.51204797 0.13596506 0.81069773 0.29502357 0.38565286 0.20577891
  0.06421235 0.625415   0.95104907 0.62188908]
 [0.69842253 0.33358835 0.28093744 0.20329632 0.24411729 0.18280519
  0.12989953 0.86172433 0.94397984 0.76359404]
 [0.78144194 0.24918118 0.44806294 0.99142653 0.6701651  0.61525055
  0.43606003 0.31176703 0.34484597 0.74375206]
 [0.3490458  0.20363231 0.66285427 0.47531471 0.77619536 0.90517951
  0.57241615 0.58088705 0.05961165 0.66572587]
 [0.22676795 0.0719514  0.6935966  0.25567376 0.79103155 0.18528693
  0.61560614 0.17315626 0.23891718 0.50834157]
 [0.4256554  0.14366744 0.48628576 0.9570176  0.36580569 0.57637479
  0.91934888 0.86059284 0.01476706 0.21501559]
 [0.76956374 0.4087849  0.20241849 0.53756459 0.44315855 0.40467296
  0.84867034

In [148]:
#Ans
mtx = np.array(np.arange(0,5))
mtx2 = np.array(np.arange(0,5)).reshape(5,1)
print(mtx+mtx2)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


Ques 8. Write a Python program to find the nearest value from a given value in an array.

In [173]:
#Ans:
Nmp=np.array([1,2,3,4,5,6,5])
print(Nmp)
Nearst = np.where(Nmp==6)
print(Nmp[Nearst[0][0] -1])

[1 2 3 4 5 6 5]
5


Ques 9. Write a Python program to find whether two random arrays A and B are equal.

In [185]:
ArrA=np.array(np.arange(10))
ArrB=np.array(np.arange(10))
ArrC= np.array(np.arange(10))
Boox = np.array_equal(ArrA,ArrB)
print(Boox)

True


Ques 10.
Consider the vector [1,2,3,4,5]
write a Python program to build a new vector with three consecutive zeros interleaved between each value.

In [298]:
Sam=np.array([1, 2, 3, 4, 5]).reshape(5,1)
apxA = np.array([0])
#print(Sam)
#y = np.append(Sam)
x = np.insert(Sam,1,[0],axis=1)
print(x)
s= np.repeat(x,1,axis=1)
print('s :' ,s)
y= np.insert(x,1,[0],axis=1)
z= np.insert(y,3,[0],axis=1)
print(z.reshape(1,20))


[[1 0]
 [2 0]
 [3 0]
 [4 0]
 [5 0]]
s : [[1 0]
 [2 0]
 [3 0]
 [4 0]
 [5 0]]
[[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]]


Ques 11. Write a Python program to find the most frequent value in an array.

In [ ]:
#Most frequent values


In [349]:
Freq=np.array([1, 2,1, 3, 4, 5,4,2,2,12])
g=np.sort(Freq,axis=0)
#?np.sort()
print(g)
#?np.repeat
count=np.bincount(Freq)
?np.bincount()
#Freq.argmax()
print(count)
print(count.argmax())

[ 1  1  2  2  2  3  4  4  5 12]
[0 2 3 1 2 1 0 0 0 0 0 0 1]
2


In [330]:
a = np.array([[1,2],[3,4],[5,6]])

#print 'First array:' 
print(a)
#print '\n'  

#print 'Axis parameter not passed. The input array is flattened before insertion.'
print (np.insert(a,3,[11,12]))
#print '\n'  
#print 'Axis parameter passed. The values array is broadcast to match input array.'

#print 'Broadcast along axis 0:' 
print(np.insert(a,1,[11],axis = 0))
#print '\n'  

#print 'Broadcast along axis 1:' 
print(np.insert(a,1,11,axis = 1))
b=np.ones(30)+2
#use eye to create a identity matrix

print(np.eye(4))
b=np.eye(4)
#use transpose to change the dimension of the array

bd=np.array(([1,2,3],[3,4,5]))
print('sum ',bd.sum(axis=1))
print(bd)
print(bd.transpose())
#

[[1 2]
 [3 4]
 [5 6]]
[ 1  2  3 11 12  4  5  6]
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
sum  [ 6 12]
[[1 2 3]
 [3 4 5]]
[[1 3]
 [2 4]
 [3 5]]
