#Numpy

In [8]:
import numpy as np
dsa=np.array([1,2,3,4,5])
ds2=np.array([5,4,3,2,1])
fd=dsa+ds2
print(fd)
print(dsa//ds2)
print(dsa%ds2)
f=(dsa+2)
print('f',f)
print(ds2.sum())

[6 6 6 6 6]
[0 0 1 2 5]
[1 2 0 0 0]
f [3 4 5 6 7]
15
