Slice Array

In [4]:
import numpy as np
import pandas as pd
x = np.array(np.linspace(2,4,9))
print(x)

[2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.  ]


In [39]:
xd=np.array(([2,3,4],
             [4,5,6],
             [6,7,8],
             [9,3,5]))
f=xd[1:2,1:]
print(f)
bcast=np.array(([0,1,2]))
nwar=xd+bcast
print(nwar)

[[5 6]]
[[ 2  4  6]
 [ 4  6  8]
 [ 6  8 10]
 [ 9  4  7]]


In [3]:
np.random.rand(2,3)

array([[0.59957838, 0.43232561, 0.57689297],
       [0.40014526, 0.42938595, 0.26397228]])

In [12]:
x = pd.Series([1,2,3],index=['a','b','c'])
x['a']
x.dtype


dtype('int64')

In [26]:
seq=[1,2,3,4,5]
val=[11,12,13,14,15]
df = pd.Series(val,seq)
df[[1,2]]
#df*2
#df+2
#df[df >13]
#df >14
#np.sqrt(df)

1    3.316625
2    3.464102
3    3.605551
4    3.741657
5    3.872983
dtype: float64

In [63]:
ind=['a','b',5,4]
f={'a':2,'b':4,5:6,7:8}
ff={'a':1,'b':4,5:6,7:4}
firm = pd.Series(ff)
firm2 = pd.Series(f)
print(sum(firm))
#f+ff
print(firm+firm2)

15
a     3
b     8
5    12
7    12
dtype: int64


In [65]:
#DataFrame